version: 2
updates:
  # Maintain dependence for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependence for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

