name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Format
        run: bun format

  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Lint
        run: bun lint

  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Build
        run: bun run build
