name: Danger JS
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  danger:
    name: Danger JS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Setup Node and Bun
        uses: jdx/mise-action@v2
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Danger
        run: bun danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
