name: Danger JS
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  danger:
    name: Danger JS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Danger
        run: bun danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
